#! python3
# rp.py - Loads first 20 searches from radiopedia

import requests, sys, webbrowser, bs4, time
print('Searching...')
res = requests.get(r'https://radiopaedia.org/search?utf8=%E2%9C%93&scope=cases&commit=Search&q=' + ' '.join(sys.argv[1:]))
res.raise_for_status()
soup = bs4.BeautifulSoup(res.text, 'html.parser')

# Open a browser tab for each result.
linkElems = soup.find_all("a", {'class': 'search-result search-result-case'})

numOpen = min(20, len(linkElems))
for i in range(numOpen):
    print (linkElems[i])
    urlToOpen = r'https://radiopaedia.org/' + linkElems[i].get('href')
    print('Opening', urlToOpen)
    webbrowser.open(urlToOpen)

print('done')
time.sleep(1)


